@startuml
start

    repeat
        repeat
            repeat
                repeat
                    partition "Step 1" {

                        #lightblue:**user:** Enter website;

                        #orange:Load questions and answers.
                        ====
                        **GET** ultimate-gay-test/v1/question;

                    }
                repeat while (Questions and answers loaded) is (Failed)

                #pink:Display questions and answers;

                partition "Step 2" {

                    #lightblue:**user:** Enter name\nand Select answers;

                    #orange:Submit selected answers.
                    ====
                    **POST** ultimate-gay-test/v1/question;

                }

            repeat while (Submission processed) is (Failed)

            partition "Step 3" {

                #lightblue:**page:** Load user results;

                #orange:Load user results.
                ====
                **GET** ultimate-gay-test/v1/user/{id};
            }

        repeat while (Results loaded) is (Failed)

        #pink:Display results;

        partition "Step 4 (Optional)" {

            #lightblue:**page:** Load all users;

            #orange:Load all users.
            ====
            **GET** ultimate-gay-test/v1/user/all;
        }

    repeat while (Results loaded) is (Failed)

    #pink:Display results;


stop
@enduml